### PR TITLE
Handle case where plugins is an object

### LINKED ISSUE #26: When plugins is an object, execution fails with "plugins.indexOf is not a function"
The `plugins` section can be specified as an array of plugin names OR as an object specifying `localPath` and `modules` (see https://serverless.com/framework/docs/providers/aws/guide/plugins#installing-plugins)

When checking the order of plugins, after this line https://github.com/iopipe/serverless-newrelic-lambda-layers/blob/df0b961515fc1abab8f51260874fdd61fd37e6d5/src/index.ts#L53, it is assumed that `plugins` is an array, so if it's an object the calls to `indexOf` will throw an error.

### PR DESCRIPTION
**Pull request by kolanos**
Closes #26

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -61,7 +61,10 @@ export default class NewRelicLambdaLayerPlugin {
       return;
     }
 
-    const plugins = _.get(this.serverless, "service.plugins", []);
+    let plugins = _.get(this.serverless, "service.plugins", []);
+    if (typeof plugins === "object") {
+      plugins = plugins.modules;
+    }
```
Comment (mrickard) [inline src/index.ts]: One thing that comes to mind is that typeof [] is "object," so this might not work as intended.  Perhaps a check on whether or not the plugins variable has length?

Comment (mrickard) [reply src/index.ts]: Or perhaps
```
    if (typeof plugins === "object" && plugins.modules) {
      plugins = plugins.modules;
    }
```
